spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: "0102"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.pavils.ecommerce.notification.PaymentNotificationRequest
server:
  port: 8060